name: CD - Staging

on:
  push:
    branches: [ develop ]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push client image
      run: |
        cd client
        docker build -t ${{ secrets.DOCKER_USERNAME }}/task-manager-client:staging-${{ github.sha }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/task-manager-client:staging-${{ github.sha }}
        docker tag ${{ secrets.DOCKER_USERNAME }}/task-manager-client:staging-${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/task-manager-client:staging-latest
        docker push ${{ secrets.DOCKER_USERNAME }}/task-manager-client:staging-latest
        
    - name: Build and push server image
      run: |
        cd server
        docker build -f Dockerfile.server -t ${{ secrets.DOCKER_USERNAME }}/task-manager-server:staging-${{ github.sha }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/task-manager-server:staging-${{ github.sha }}
        docker tag ${{ secrets.DOCKER_USERNAME }}/task-manager-server:staging-${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/task-manager-server:staging-latest
        docker push ${{ secrets.DOCKER_USERNAME }}/task-manager-server:staging-latest
        
    - name: Deploy to staging server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.STAGING_HOST }}
        username: ${{ secrets.STAGING_USERNAME }}
        key: ${{ secrets.STAGING_SSH_KEY }}
        script: |
          cd /opt/task-manager
          docker-compose pull
          docker-compose -f docker-compose.staging.yml up -d
          docker system prune -f
          
    - name: Health check staging
      run: |
        sleep 30
        curl -f http://${{ secrets.STAGING_HOST }}:8080 || exit 1 